version: "3.9"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - django_network

  web:
    image: alexandrearaujo01/djangovogue:latest
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - django_network
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: db

networks:
  django_network:

volumes:
  db_data:
