# Generated by Django 4.2.13 on 2024-05-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[(1, 'Camisa'), (2, 'Jeans'), (3, 'Vestido'), (4, 'Short'), (5, 'Casaco'), (6, 'Acessorios')], default='outros', max_length=20),
        ),
    ]
