# Generated by Django 4.2.13 on 2024-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='parcela',
            field=models.CharField(default='MUDAR', max_length=300, verbose_name='Parcela'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Camisa'), (2, 'Jeans'), (3, 'Vestido'), (4, 'Short'), (5, 'Casaco'), (6, 'Acessorios'), (7, 'Outros')], default=7),
        ),
    ]
