# Generated by Django 4.2.13 on 2024-05-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_produto_parcela_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Camisa'), (2, 'Jeans'), (3, 'Vestido'), (4, 'Short'), (5, 'Casaco'), (6, 'Acessorios'), (7, 'Outros')], default=7),
        ),
    ]
