# Generated by Django 4.2.13 on 2024-05-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_produto_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='numero_parcela',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero Parcela'),
        ),
    ]
